=== easitab/EPR.GlobalFunctions/tests/data/installerSettings.schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
	  "Parameters": {
		"type": "object",
		"properties": {
		  "InstanceID": {
			"type": "null"
		  },
		  "InstallLocation": {
			"type": "string"
		  },
		  "SystemName": {
			"type": "string"
		  },
		  "Port": {
			"type": "integer"
		  },
		  "IgnoreDirectoryStructure": {
			"type": "string"
		  },
		  "TomcatXmx": {
			"type": "integer"
		  },
		  "SendInstallationDetailsToEasit": {
			"type": "string"
		  }
		},
		"required": [
		  "InstanceID",
		  "InstallLocation",
		  "SystemName",
		  "Port",
		  "IgnoreDirectoryStructure",
		  "TomcatXmx",
		  "SendInstallationDetailsToEasit"
		]
	  },
	  "easitRootDirectoryName": {
		"type": "string"
	  },
	  "easitSubFolders": {
		"type": "array",
		"items": [
		  {
			"type": "string"
		  }
		]
	  },
	  "systemSubFolders": {
		"type": "array",
		"items": [
		  {
			"type": "string"
		  },
		  {
			"type": "string"
		  },
		  {
			"type": "string"
		  }
		]
	  },
	  "systemSubFoldersFromArchive": {
		"type": "array",
		"items": [
		  {
			"type": "string"
		  },
		  {
			"type": "string"
		  },
		  {
			"type": "string"
		  }
		]
	  },
	  "tomcatSubFolders": {
		"type": "array",
		"items": [
		  {
			"type": "string"
		  }
		]
	  },
	  "tomcatSubFoldersFromArchive": {
		"type": "array",
		"items": [
		  {
			"type": "string"
		  }
		]
	  },
	  "tomcatFilesToReplaceSystemPortIn": {
		"type": "array",
		"items": [
		  {
			"type": "string"
		  }
		]
	  },
	  "configFilesToReplaceSystemRootIn": {
		"type": "array",
		"items": [
		  {
			"type": "string"
		  }
		]
	  },
	  "configFilesToReplacePasswordIn": {
		"type": "array",
		"items": [
		  {
			"type": "string"
		  }
		]
	  },
	  "configFilesToReplacepwshExecutableIn": {
		"type": "array",
		"items": [
		  {
			"type": "string"
		  }
		]
	  },
	  "FeedbackSettings": {
		"type": "object",
		"properties": {
		  "url": {
			"type": "string"
		  },
		  "apikey": {
			"type": "string"
		  },
		  "postBody": {
			"type": "object",
			"properties": {
			  "importHandlerIdentifier": {
				"type": "string"
			  },
			  "properties": {
				"type": "array",
				"items": [
				  {
					"type": "string"
				  },
				  {
					"type": "string"
				  },
				  {
					"type": "string"
				  },
				  {
					"type": "string"
				  },
				  {
					"type": "string"
				  },
				  {
					"type": "string"
				  },
				  {
					"type": "string"
				  }
				]
			  }
			},
			"required": [
			  "importHandlerIdentifier",
			  "properties"
			]
		  }
		},
		"required": [
		  "url",
		  "apikey",
		  "postBody"
		]
	  }
	},
	"required": [
	  "Parameters",
	  "easitRootDirectoryName",
	  "easitSubFolders",
	  "systemSubFolders",
	  "systemSubFoldersFromArchive",
	  "tomcatSubFolders",
	  "tomcatSubFoldersFromArchive",
	  "tomcatFilesToReplaceSystemPortIn",
	  "configFilesToReplaceSystemRootIn",
	  "configFilesToReplacePasswordIn",
	  "configFilesToReplacepwshExecutableIn",
	  "FeedbackSettings"
	]
  }

=== easitab/EPR.GlobalFunctions/tests/data/installerSettings.json
{
    "Parameters": {
      "InstanceID": null,
      "InstallLocation": "D:\\",
      "SystemName": "Test",
      "Port": 8085,
      "IgnoreDirectoryStructure": "false",
      "TomcatXmx": 512,
      "SendInstallationDetailsToEasit": "true"
    },
    "easitRootDirectoryName": "Easit",
    "easitSubFolders": [
      "_Backup"
    ],
    "systemSubFolders": [
      "config",
      "scripts",
      "tomcat"
    ],
    "systemSubFoldersFromArchive": [
      "config",
      "scripts",
      "tomcat"
    ],
    "tomcatSubFolders": [
      "jre"
    ],
    "tomcatSubFoldersFromArchive": [
      "jre"
    ],
    "tomcatFilesToReplaceSystemPortIn": [
      "server.xml"
    ],
    "configFilesToReplaceSystemRootIn": [
      "application.properties"
    ],
    "configFilesToReplacePasswordIn": [
      "users.properties"
    ],
    "configFilesToReplacepwshExecutableIn": [
      "application.properties"
    ],
    "FeedbackSettings": {
      "url": "https:/test.easit.com/easit/integration-api/items",
      "apikey": "ZgA5ADgAYgAyADIAYgBjADgAMABlADUANwBhAGEANwA1ADkAZABhAGIAMwBlADgANABmAGQANgAzAGMAOQA4ADkAYgA4ADEAMwBjADIAYQA2ADAANQA2ADEAYgAwAGMAYwBkADQANABmADMAZQA1AGUAYQBiADEAZgBiAGMAMAA=",
      "postBody": {
        "importHandlerIdentifier": "eprInstallationFeedback",
        "properties": [
          "InstanceID",
          "OSVersion",
          "SystemRootDirectory",
          "TomcatRootDirectory",
          "TomcatVersion",
          "JavaVersion",
          "ServiceName"
        ]
      }
    }
  }
